version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  express:
    build: .
    container_name: express_app
    ports:
      - "8383:8383"
    environment:
      - PORT=8383
      - MONGO_URL=mongodb://mongo:27017/PostAndCommentService
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongo
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo

volumes:
  mongo_data:
